In [ ]:
import numpy as np

4.1 Exercise on Functions:

 Task- 1:
 Create a Python program that converts between different units of measurement.
 • The program should:
 1. Prompt the user to choose the type of conversion (e.g., length, weight, volume).
 2. Ask the user to input the value to be converted.
 3. Perform the conversion and display the result.
 4. Handle potential errors, such as invalid input or unsupported conversion types.
 • Requirements:
 1. Functions: Define at least one function to perform the conversion.
 2. Error Handling: Use try-except blocks to handle invalid input (e.g., non-numeric values).
 3. User Input: Prompt the user to select the conversion type and input the value.
 4. Docstrings: Include a docstring in your function to describe its purpose, parameters, and
 return value.
 • Conversion Options:
 1. Length:– Convert meters (m) to feet (ft).– Convert feet (ft) to meters (m).
 2. Weight:– Convert kilograms (kg) to pounds (lbs).– Convert pounds (lbs) to kilograms (kg).
 3. Volume:– Convert liters (L) to gallons (gal).– Convert gallons (gal) to liters (L)

In [ ]:
def convert_length(value, unit):
    if unit == 'm':
        return value * 3.28084
    elif unit == 'ft':
        return value / 3.28084
    else:
        raise ValueError("Unsupported unit for length conversion.")

def convert_weight(value, unit):
    if unit == 'kg':
        return value * 2.20462
    elif unit == 'lbs':
        return value / 2.20462
    else:
        raise ValueError("Unsupported unit for weight conversion.")

def convert_volume(value, unit):
    if unit == 'L':
        return value * 0.264172
    elif unit == 'gal':
        return value / 0.264172
    else:
        raise ValueError("Unsupported unit for volume conversion.")

def main():
    print("Choose the type of conversion:")
    print("1. Length")
    print("2. Weight")
    print("3. Volume")

    try:
        choice = int(input("Enter the number corresponding to your choice: "))

        if choice == 1:
            value = float(input("Enter the value to convert: "))
            unit = input("Enter the unit (m for meters, ft for feet): ")
            result = convert_length(value, unit)
            print(f"Converted value: {result} {'feet' if unit == 'm' else 'meters'}")

        elif choice == 2:
            value = float(input("Enter the value to convert: "))
            unit = input("Enter the unit (kg for kilograms, lbs for pounds): ")
            result = convert_weight(value, unit)
            print(f"Converted value: {result} {'pounds' if unit == 'kg' else 'kilograms'}")

        elif choice == 3:
            value = float(input("Enter the value to convert: "))
            unit = input("Enter the unit (L for liters, gal for gallons): ")
            result = convert_volume(value, unit)
            print(f"Converted value: {result} {'gallons' if unit == 'L' else 'liters'}")

        else:
            print("Invalid choice. Please select 1, 2, or 3.")

    except ValueError as e:
        print(f"Invalid input: {e}")

if __name__ == "__main__":
    main()


Choose the type of conversion:
1. Length
2. Weight
3. Volume
Enter the number corresponding to your choice: 2
Enter the value to convert: 95
Enter the unit (kg for kilograms, lbs for pounds): kg
Converted value: 209.4389 pounds


 Task- 2:
 Create a Python program that performs various mathematical operations on a list of numbers.
 • The Program should:
 1. Prompt the user to choose an operation (e.g., find the sum, average, maximum, or minimum
 of the numbers).
 2. Ask the user to input a list of numbers (separated by spaces).
 3. Perform the selected operation and display the result.
 4. Handle potential errors, such as invalid input or empty lists.
 • Requirements:
 1. Functions: Define at least one function for each operation (sum, average, maximum, mini
mum).
 2. Error Handling: Use try-except blocks to handle invalid input (e.g., non-numeric values or
 empty lists).
 3. User Input: Prompt the user to select the operation and input the list of numbers.
 4. Docstrings: Include a docstring in each function to describe its purpose, parameters, and
 return value

In [ ]:
def calculate_sum(numbers):
    """
    Calculate the sum of a list of numbers.

    Parameters:
    numbers (list of float): The list of numbers to sum.

    Returns:
    float: The sum of the numbers.
    """
    return sum(numbers)

def calculate_average(numbers):
    """
    Calculate the average of a list of numbers.

    Parameters:
    numbers (list of float): The list of numbers to average.

    Returns:
    float: The average of the numbers.
    """
    return sum(numbers) / len(numbers) if numbers else 0

def find_maximum(numbers):
    """
    Find the maximum value in a list of numbers.

    Parameters:
    numbers (list of float): The list of numbers to find the maximum in.

    Returns:
    float: The maximum value.
    """
    return max(numbers) if numbers else None

def find_minimum(numbers):
    """
    Find the minimum value in a list of numbers.

    Parameters:
    numbers (list of float): The list of numbers to find the minimum in.

    Returns:
    float: The minimum value.
    """
    return min(numbers) if numbers else None

def main():
    print("Choose an operation:")
    print("1. Sum")
    print("2. Average")
    print("3. Maximum")
    print("4. Minimum")

    try:
        choice = int(input("Enter the number corresponding to your choice: "))
        user_input = input("Enter a list of numbers separated by spaces: ")
        numbers = list(map(float, user_input.split()))

        if not numbers:
            raise ValueError("The list of numbers is empty.")

        if choice == 1:
            result = calculate_sum(numbers)
            print(f"Sum: {result}")
        elif choice == 2:
            result = calculate_average(numbers)
            print(f"Average: {result}")
        elif choice == 3:
            result = find_maximum(numbers)
            print(f"Maximum: {result}")
        elif choice == 4:
            result = find_minimum(numbers)
            print(f"Minimum: {result}")
        else:
            print("Invalid choice. Please select 1, 2, 3, or 4.")

    except ValueError as e:
        print(f"Invalid input: {e}")

if __name__ == "__main__":
    main()


Choose an operation:
1. Sum
2. Average
3. Maximum
4. Minimum
Enter the number corresponding to your choice: 4
Enter a list of numbers separated by spaces: 99 78
Minimum: 78.0


 Exercise on List Manipulation:
 1. Extract Every Other Element:
 Write a Python function that extracts every other element from a list, starting from the first element.
 • Requirements:– Define a function extract
 every
 other(lst) that takes a list lst as input and returns a
 new list containing every other element from the original list.– Example: For the input [1, 2, 3, 4, 5, 6], the output should be [1, 3, 5].
 2. Slice a Sublist:
 Write a Python function that returns a sublist from a given list, starting from a specified index and
 ending at another specified index.
 • Requirements:– Define a function get
 sublist(lst, start, end) that takes a list lst, a starting index
 start, and an ending index end as input and returns the sublist from start to end (inclusive).– Example: For the input [1, 2, 3, 4, 5, 6] with start=2 and end=4, the output should
 be [3, 4, 5].
 3. Reverse a List Using Slicing:
 Write a Python function that reverses a list using slicing.
 • Requirements:– Define a function reverse
 slicing.
 list(lst) that takes a list lst and returns a reversed list using– Example: For the input [1, 2, 3, 4, 5], the output should be [5, 4, 3, 2, 1].
 4. Remove the First and Last Elements:
 Write a Python function that removes the first and last elements of a list and returns the resulting
 sublist.
 • Requirements:– Defineafunction remove
 first
 last(lst) that takes a list lst and returns a sublist without
 the first and last elements using slicing.– Example: For the input [1, 2, 3, 4, 5], the output should be [2, 3, 4].
 5. Get the First n Elements:
 Write a Python function that extracts the first n elements from a list.
 • Requirements:– Define a function get
 first
 n(lst, n) that takes a list lst and an integer n as input and
 returns the first n elements of the list using slicing.– Example: For the input [1, 2, 3, 4, 5] with n=3, the output should be [1, 2, 3].
 6. Extract Elements from the End:
 Write a Python function that extracts the last n elements of a list using slicing.
 • Requirements:– Define a function get
 last
 n(lst, n) that takes a list lst and an integer n as input and
 returns the last n elements of the list.– Example: For the input [1, 2, 3, 4, 5] with n=2, the output should be [4, 5].
 7. Extract Elements in Reverse Order:
 Write a Python function that extracts a list of elements in reverse order starting from the second-to-last
 element and skipping one element in between.
 • Requirements:– Define a function reverse
 skip(lst) that takes a list lst and returns a new list containing
 every second element starting from the second-to-last, moving backward.– Example: For the input [1, 2, 3, 4, 5, 6], the output should be [5, 3, 1]

In [ ]:
def extract_every_other(lst):
    return lst[::2]

def get_sublist(lst, start, end):
    return lst[start:end+1]

def reverse_slicing_list(lst):
    return lst[::-1]

def remove_first_last(lst):
    return lst[1:-1]

def get_first_n(lst, n):
    return lst[:n]

def get_last_n(lst, n):
    return lst[-n:]

def reverse_skip(lst):
    return lst[-2::-2]

example_list = [1, 2, 3, 4, 5, 6]

print(extract_every_other(example_list))
print(get_sublist(example_list, 2, 4))
print(reverse_slicing_list(example_list))
print(remove_first_last(example_list))
print(get_first_n(example_list, 3))
print(get_last_n(example_list, 2))
print(reverse_skip(example_list))


[1, 3, 5]
[3, 4, 5]
[6, 5, 4, 3, 2, 1]
[2, 3, 4, 5]
[1, 2, 3]
[5, 6]
[5, 3, 1]


Exercise on Nested List:
 1. Flatten a Nested List:
 Write a Python function that takes a nested list and flattens it into a single list, where all the elements
 are in a single dimension.
 • Requirements:– Define a function flatten(lst) that takes a nested list lst and returns a flattened version
 of the list.– Example: For the input [[1, 2], [3, 4], [5]], the output should be [1, 2, 3, 4, 5].
 2. Accessing Nested List Elements:
 Write a Python function that extracts a specific element from a nested list given its indices.
 • Requirements:– Define a function access
 nested
 element(lst, indices) that takes a nested list lst and
 a list of indices indices, and returns the element at that position.– Example: For the input lst = [[1, 2, 3], [4, 5, 6], [7, 8, 9]] with indices = [1,
 2], the output should be 6.
 3. Sum of All Elements in a Nested List:
 Write a Python function that calculates the sum of all the numbers in a nested list (regardless of depth).
 • Requirements:– Define a function sum
 nested(lst) that takes a nested list lst and returns the sum of all
 the elements.– Example: For the input [[1, 2], [3, [4, 5]], 6], the output should be 21.
 4. Remove Specific Element from a Nested List:
 Write a Python function that removes all occurrences of a specific element from a nested list.
 • Requirements:– Define a function remove
 element(lst, elem) that removes elem from lst and returns the
 modified list.– Example: Fortheinput lst = [[1, 2], [3, 2], [4, 5]]andelem = 2,theoutputshould
 be [[1], [3], [4, 5]].
 5. Find the Maximum Element in a Nested List:
 Write a Python function that finds the maximum element in a nested list (regardless of depth).
 • Requirements:– Define a function find
 element.
 max(lst) that takes a nested list lst and returns the maximum– Example: For the input [[1, 2], [3, [4, 5]], 6], the output should be 6.
 6. Count Occurrences of an Element in a Nested List:
 Write a Python function that counts how many times a specific element appears in a nested list.
 • Requirements:– Define a function count
 occurrences(lst, elem) that counts the occurrences of elem in
 the nested list lst.– Example: Fortheinput lst = [[1, 2], [2, 3], [2, 4]]andelem = 2,theoutputshould
 be 3.
 7. Flatten a List of Lists of Lists:
 Write a Python function that flattens a list of lists of lists into a single list, regardless of the depth.
 • Requirements:– Define a function deep
 flatten(lst) that takes a deeply nested list lst and returns a single
 f
 lattened list.– Example: For the input [[[1, 2], [3, 4]], [[5, 6], [7, 8]]], the output should be
 [1, 2, 3, 4, 5, 6, 7, 8].
 8. Nested List Average:
 Write a Python function that calculates the average of all elements in a nested list.
 • Requirements:– Define a function average
 of all the elements.
 nested(lst) that takes a nested list lst and returns the average– Example: For the input [[1, 2], [3, 4], [5, 6]], the output should be 3.5

In [ ]:
def flatten(lst):
    flat_list = []
    for item in lst:
        if isinstance(item, list):
            flat_list.extend(flatten(item))
        else:
            flat_list.append(item)
    return flat_list

def access_nested_element(lst, indices):
    for index in indices:
        lst = lst[index]
    return lst

def sum_nested(lst):
    total = 0
    for item in lst:
        if isinstance(item, list):
            total += sum_nested(item)
        else:
            total += item
    return total

def remove_element(lst, elem):
    if not isinstance(lst, list):
        return lst
    return [remove_element(item, elem) for item in lst if item != elem]

def find_element_max(lst):
    max_element = float('-inf')
    for item in lst:
        if isinstance(item, list):
            max_element = max(max_element, find_element_max(item))
        else:
            max_element = max(max_element, item)
    return max_element

def count_occurrences(lst, elem):
    count = 0
    for item in lst:
        if isinstance(item, list):
            count += count_occurrences(item, elem)
        elif item == elem:
            count += 1
    return count

def deep_flatten(lst):
    flat_list = []
    for item in lst:
        if isinstance(item, list):
            flat_list.extend(deep_flatten(item))
        else:
            flat_list.append(item)
    return flat_list

def average_nested(lst):
    total, count = 0, 0
    for item in lst:
        if isinstance(item, list):
            sub_total, sub_count = average_nested(item)
            total += sub_total
            count += sub_count
        else:
            total += item
            count += 1
    return total, count

nested_list = [[1, 2], [3, [4, 5]], 6]

print(flatten(nested_list))
print(access_nested_element(nested_list, [1, 1, 0]))
print(sum_nested(nested_list))
print(remove_element(nested_list, 2))
print(find_element_max(nested_list))
print(count_occurrences(nested_list, 2))
print(deep_flatten([[[1, 2], [3, 4]], [[5, 6], [7, 8]]]))
total, count = average_nested([[1, 2], [3, 4], [5, 6]])
print(total / count)


[1, 2, 3, 4, 5, 6]
4
21
[[1], [3, [4, 5]], 6]
6
1
[1, 2, 3, 4, 5, 6, 7, 8]
3.5


 Problem- 1: Array Creation:
 Complete the following Tasks:
 1. Initialize an empty array with size 2X2.
 2. Initialize an all one array with size 4X2.
 3. Return a new array of given shape and type, filled with fill value.{Hint: np.full}
 4. Return a new array of zeros with same shape and type as a given array.{Hint: np.zeros like}
 5. Return a new array of ones with same shape and type as a given array.{Hint: np.ones like}
 6. For an existing list new_list = [1,2,3,4] convert to an numpy array.{Hint: np.array()}

In [ ]:
empty_array = np.empty((2, 2))
print("Empty Array:", empty_array)
ones_array = np.ones((4, 2))
print("Ones Array:", ones_array)
fill_array = np.full((3, 3), 7)
print("Full Array:", fill_array)
reference_array = np.array([[1, 2, 3], [4, 5, 6]])
zeros_like_array = np.zeros_like(reference_array)
print("Zeros Like Array:", zeros_like_array)
ones_like_array = np.ones_like(reference_array)
print("Ones Like Array:", ones_like_array)
new_list = [1, 2, 3, 4]
numpy_array = np.array(new_list)
print("Numpy Array:", numpy_array)


Empty Array: [[2.06803424e-316 0.00000000e+000]
 [1.00030997e-310 1.39067116e-308]]
Ones Array: [[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]
Full Array: [[7 7 7]
 [7 7 7]
 [7 7 7]]
Zeros Like Array: [[0 0 0]
 [0 0 0]]
Ones Like Array: [[1 1 1]
 [1 1 1]]
Numpy Array: [1 2 3 4]


Problem- 2: Array Manipulation: Numerical Ranges and Array indexing:
 Complete the following tasks:
 1. Create an array with values ranging from 10 to 49. {Hint:np.arrange()}.
 2. Create a 3X3 matrix with values ranging from 0 to 8.
 {Hint:look for np.reshape()}
 3. Create a 3X3 identity matrix.{Hint:np.eye()}
 4. Create a random array of size 30 and find the mean of the array.
 {Hint:check for np.random.random() and array.mean() function}
 5. Create a 10X10 array with random values and find the minimum and maximum values.
 6. Create a zero array of size 10 and replace 5th element with 1.
 7. Reverse an array arr = [1,2,0,0,4,0].
 8. Create a 2d array with 1 on border and 0 inside.
 9. Create a 8X8 matrix and fill it with a checkerboard pattern

In [ ]:
array_1 = np.arange(10, 50)
print("Array with values from 10 to 49:", array_1)

matrix_2 = np.arange(9).reshape(3, 3)
print("3x3 Matrix with values from 0 to 8:\n", matrix_2)

identity_matrix = np.eye(3)
print("3x3 Identity Matrix:\n", identity_matrix)

random_array = np.random.random(30)
mean_value = random_array.mean()
print("Mean of the random array:", mean_value)

random_matrix = np.random.random((10, 10))
min_value = random_matrix.min()
max_value = random_matrix.max()
print("Minimum value:", min_value, "Maximum value:", max_value)

zero_array = np.zeros(10)
zero_array[4] = 1
print("Zero array with 5th element as 1:", zero_array)

arr = np.array([1, 2, 0, 0, 4, 0])
reversed_arr = arr[::-1]
print("Reversed array:", reversed_arr)

border_array = np.ones((5, 5))
border_array[1:-1, 1:-1] = 0
print("2D array with border 1 and inside 0:\n", border_array)

checkerboard = np.zeros((8, 8), dtype=int)
checkerboard[1::2, ::2] = 1
checkerboard[::2, 1::2] = 1
print("8x8 Checkerboard pattern:\n", checkerboard)


Array with values from 10 to 49: [10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]
3x3 Matrix with values from 0 to 8:
 [[0 1 2]
 [3 4 5]
 [6 7 8]]
3x3 Identity Matrix:
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
Mean of the random array: 0.4760437083553528
Minimum value: 0.003961509668924723 Maximum value: 0.9871774042979938
Zero array with 5th element as 1: [0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
Reversed array: [0 4 0 0 2 1]
2D array with border 1 and inside 0:
 [[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]
8x8 Checkerboard pattern:
 [[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


 Problem- 3: Array Operations:
 For the following arrays:
 x = np.array([[1,2],[3,5]]) and y = np.array([[5,6],[7,8]]);
 v = np.array([9,10]) and w = np.array([11,12]);
 Complete all the task using numpy:
 1. Add the two array.
 2. Subtract the two array.
 3. Multiply the array with any integers of your choice.
 4. Find the square of each element of the array.
 5. Find the dot product between: v(and)w ; x(and)v ; x(and)y.
 6. Concatenate x(and)y along row and Concatenate v(and)w along column.
 {Hint:try np.concatenate() or np.vstack() functions.
 7. Concatenate x(and)v; if you get an error, observe and explain why did you get the error

In [ ]:
x = np.array([[1, 2], [3, 5]])
y = np.array([[5, 6], [7, 8]])
v = np.array([9, 10])
w = np.array([11, 12])

addition = x + y

subtraction = x - y

multiplication_x = x * 2

square_x = np.square(x)

dot_v_w = np.dot(v, w)
dot_x_v = np.dot(x, v)
dot_x_y = np.dot(x, y)

concat_xy_row = np.concatenate((x, y), axis=0)
concat_vw_col = np.concatenate((v.reshape(-1, 1), w.reshape(-1, 1)), axis=1)

try:
    concat_xv = np.concatenate((x, v), axis=0)
except ValueError as e:
    concat_xv_error = str(e)

print("1. Addition of x and y:\n", addition)
print("\n2. Subtraction of x and y:\n", subtraction)
print("\n3. Multiplication of x by 2:\n", multiplication_x)
print("\n4. Square of each element in x:\n", square_x)
print("\n5. Dot Products:")
print("   - Dot product of v and w:", dot_v_w)
print("   - Dot product of x and v:", dot_x_v)
print("   - Dot product of x and y:\n", dot_x_y)
print("\n6. Concatenation:")
print("   - Concatenation of x and y along rows:\n", concat_xy_row)
print("   - Concatenation of v and w along columns:\n", concat_vw_col)
print("\n7. Attempt to concatenate x and v resulted in an error:")
print("   ", concat_xv_error)


1. Addition of x and y:
 [[ 6  8]
 [10 13]]

2. Subtraction of x and y:
 [[-4 -4]
 [-4 -3]]

3. Multiplication of x by 2:
 [[ 2  4]
 [ 6 10]]

4. Square of each element in x:
 [[ 1  4]
 [ 9 25]]

5. Dot Products:
   - Dot product of v and w: 219
   - Dot product of x and v: [29 77]
   - Dot product of x and y:
 [[19 22]
 [50 58]]

6. Concatenation:
   - Concatenation of x and y along rows:
 [[1 2]
 [3 5]
 [5 6]
 [7 8]]
   - Concatenation of v and w along columns:
 [[ 9 11]
 [10 12]]

7. Attempt to concatenate x and v resulted in an error:
    all the input arrays must have same number of dimensions, but the array at index 0 has 2 dimension(s) and the array at index 1 has 1 dimension(s)


 Problem- 4: Matrix Operations:
 • For the following arrays:
 A = np.array([[3,4],[7,8]]) and B = np.array([[5,3],[2,1]]);
 Prove following with Numpy:
 1. Prove A.A−1 = I.
 2. Prove AB= BA.
 3. Prove (AB)T = BTAT.
 • Solve the following system of Linear equation using Inverse Methods.
 2x −3y+z =−1
 x −y+2z =−3
 3x +y−z =9
 {Hint: First use Numpy array to represent the equation in Matrix form. Then Solve for: AX = B}
 • Now: solve the above equation using np.linalg.inv function.{Explore more about ”linalg” func
tion of Numpy}

In [ ]:
A = np.array([[3, 4],
              [7, 8]])
B = np.array([[5, 3],
              [2, 1]])
A_inv = np.linalg.inv(A)
identity = np.dot(A, A_inv)
print("A * A⁻¹ =\n", identity)


AB = np.dot(A, B)
BA = np.dot(B, A)
print("\nAB =\n", AB)
print("\nBA =\n", BA)
if np.allclose(AB, BA):
    print("\nConclusion: AB equals BA.")
else:
    print("\nConclusion: AB does NOT equal BA.")  #


AB_transpose = np.transpose(AB)
B_transpose_A_transpose = np.dot(np.transpose(B), np.transpose(A))
print("\n(AB)ᵀ =\n", AB_transpose)
print("\nBᵀAᵀ =\n", B_transpose_A_transpose)
if np.allclose(AB_transpose, B_transpose_A_transpose):
    print("\nConclusion: (AB)ᵀ equals BᵀAᵀ.")
else:
    print("\nConclusion: (AB)ᵀ does NOT equal BᵀAᵀ.")


M = np.array([[2, -3,  1],
              [1, -1,  2],
              [3,  1, -1]])
b = np.array([-1, -3, 9])


M_inv = np.linalg.inv(M)
X = np.dot(M_inv, b)
print("\nSolution using inverse method (X = [x, y, z]):\n", X)

X_solve = np.linalg.solve(M, b)
print("\nSolution using np.linalg.solve:\n", X_solve)


A * A⁻¹ =
 [[1.00000000e+00 0.00000000e+00]
 [1.77635684e-15 1.00000000e+00]]

AB =
 [[23 13]
 [51 29]]

BA =
 [[36 44]
 [13 16]]

Conclusion: AB does NOT equal BA.

(AB)ᵀ =
 [[23 51]
 [13 29]]

BᵀAᵀ =
 [[23 51]
 [13 29]]

Conclusion: (AB)ᵀ equals BᵀAᵀ.

Solution using inverse method (X = [x, y, z]):
 [ 2.  1. -2.]

Solution using np.linalg.solve:
 [ 2.  1. -2.]


 10.2 Experiment: How Fast is Numpy?
 In this exercise, you will compare the performance and implementation of operations using plain Python
 lists (arrays) and NumPy arrays. Follow the instructions:
 1. Element-wise Addition:
 • Using Python Lists, perform element-wise addition of two lists of size 1,000,000. Measure
 and Print the time taken for this operation.
 • Using Numpy Arrays, Repeat the calculation and measure and print the time taken for
 this operation.
 2. Element-wise Multiplication
 • Using Python Lists, perform element-wise multiplication of two lists of size 1,000,000.
 Measure and Print the time taken for this operation.
 • Using Numpy Arrays, Repeat the calculation and measure and print the time taken for
 this operation.
 3. Dot Product
 • Using Python Lists, compute the dot product of two lists of size 1,000,000. Measure and
 Print the time taken for this operation.
 • Using Numpy Arrays, Repeat the calculation and measure and print the time taken for
 this operation.
 4. Matrix Multiplication
 • Using Python lists, perform matrix multiplication of two matrices of size 1000x1000. Mea
sure and print the time taken for this operation.
 • Using NumPy arrays, perform matrix multiplication of two matrices of size 1000x1000.
 Measure and print the time taken for this operation.

In [ ]:
import time
import random

size = 1_000_000

list1 = [random.random() for _ in range(size)]
list2 = [random.random() for _ in range(size)]

start = time.time()
result_add_list = [list1[i] + list2[i] for i in range(size)]
end = time.time()
print("Python list element-wise addition time:", end - start, "seconds")

np_arr1 = np.array(list1)
np_arr2 = np.array(list2)
start = time.time()
result_add_np = np_arr1 + np_arr2
end = time.time()
print("NumPy array element-wise addition time:", end - start, "seconds")



start = time.time()
result_mult_list = [list1[i] * list2[i] for i in range(size)]
end = time.time()
print("Python list element-wise multiplication time:", end - start, "seconds")
start = time.time()
result_mult_np = np_arr1 * np_arr2
end = time.time()
print("NumPy array element-wise multiplication time:", end - start, "seconds")



start = time.time()
dot_product_list = sum(list1[i] * list2[i] for i in range(size))
end = time.time()
print("Python list dot product time:", end - start, "seconds")
start = time.time()
dot_product_np = np.dot(np_arr1, np_arr2)
end = time.time()
print("NumPy array dot product time:", end - start, "seconds")



n = 1000

print("\nGenerating 1000x1000 matrices for Python lists multiplication (this may take a moment)...")
A_list = [[random.random() for _ in range(n)] for _ in range(n)]
B_list = [[random.random() for _ in range(n)] for _ in range(n)]
start = time.time()
C_list = [[sum(A_list[i][k] * B_list[k][j] for k in range(n)) for j in range(n)]
          for i in range(n)]
end = time.time()
print("Python list matrix multiplication time:", end - start, "seconds")
A_np = np.array(A_list)
B_np = np.array(B_list)
start = time.time()
C_np = np.dot(A_np, B_np)
end = time.time()
print("NumPy matrix multiplication time:", end - start, "seconds")


Python list element-wise addition time: 0.08059334754943848 seconds
NumPy array element-wise addition time: 0.004726409912109375 seconds
Python list element-wise multiplication time: 0.08043193817138672 seconds
NumPy array element-wise multiplication time: 0.0045320987701416016 seconds
Python list dot product time: 0.0700235366821289 seconds
NumPy array dot product time: 0.0014848709106445312 seconds

Generating 1000x1000 matrices for Python lists multiplication (this may take a moment)...
Python list matrix multiplication time: 176.87799620628357 seconds
NumPy matrix multiplication time: 0.0664665699005127 seconds
